In [1]:
from nd2reader import ND2Reader
import tifffile
import numpy as np
from matplotlib import pyplot as plt
import glob
import sys
import numpy as np
import os
import importlib

# os.chdir('/Users/bebr1814/projects/anabaena/scratch_data/')

In [2]:
# It apparently isn't possible to get the path of this notebook automatically, so set this when you need it
sys.path.append('/Users/bebr1814/projects/anabaena/src')
from file_formatting.ImageHandler import ImageHandler as ImageHandler

In [3]:
%load_ext autoreload
%autoreload 1
%aimport file_formatting.ImageHandler

In [4]:
files = glob.glob('/Users/bebr1814/projects/anabaena/scratch_data/20241010_ZMB_Anabaena/20241010_001_ZMB00*/nd2/*.nd2')
f = files[0]
f

'/Users/bebr1814/projects/anabaena/scratch_data/20241010_ZMB_Anabaena/20241010_001_ZMB001/nd2/09.nd2'

In [5]:
# select files to convert
files = glob.glob('/Users/bebr1814/projects/anabaena/scratch_data/20241010_ZMB_Anabaena/20241010_001_ZMB00*/nd2/*.nd2')

for f in files:
	print(f)

	# make a dir
	maindir = os.path.dirname(os.path.dirname(f))
	os.makedirs(os.path.join(maindir,'tif'), exist_ok=True)
	outfile = os.path.join(maindir,'tif',os.path.basename(f)).replace('.nd2', '.tif')

	processor = ImageHandler(
		input_file=f,
		output_dir=os.path.join(maindir,'tif'),
		# selected_channels=selected_channels,
	)
	processor.setup_reader()
	processor.process_and_save_frames(
		save_png=False,
		save_frames=False,
		save_fov=True,
		save_combined_tiff=True
	)

	# ih = ImageHandler(f)
	# ih.read_image()
	# ih.save_image(outfile)
	# print(f'Converted {f} to {outfile}')


/Users/bebr1814/projects/anabaena/scratch_data/20241010_ZMB_Anabaena/20241010_001_ZMB001/nd2/09.nd2
ND2 File Metadata: {'height': 2044, 'width': 2048, 'date': datetime.datetime(2024, 10, 10, 12, 12, 6), 'fields_of_view': [0], 'frames': [0], 'z_levels': [], 'z_coordinates': [2147.1], 'total_images_per_channel': 1, 'channels': ['Mono', 'Cy5', 'Texas Red'], 'pixel_microns': 0.1625, 'num_frames': 1, 'experiment': {'description': '', 'loops': []}, 'events': []}
ND2 Image Shape: {'x': 2048, 'y': 2044, 'c': 3, 't': 1}
Reading input file /Users/bebr1814/projects/anabaena/scratch_data/20241010_ZMB_Anabaena/20241010_001_ZMB001/nd2/09.nd2
['x', 'y', 'c']
(1, 2044, 2048, 3)
(3, 2044, 2048)
[[[32230. 33283. 33597. ... 31014. 31555. 30221.]
  [32182. 33152. 34201. ... 30818. 31065. 30262.]
  [32204. 33610. 33926. ... 31143. 30968. 29778.]
  ...
  [33960. 35333. 35292. ... 34755. 34759. 33226.]
  [33596. 34932. 35516. ... 34890. 34011. 33072.]
  [33571. 35362. 35308. ... 34212. 34336. 32880.]]

 [[  